apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  selector:
    matchLabels:
      app: manager-service
  replicas: 1
  template:
    metadata:
      labels:
        app: manager-service
    spec:
      containers:
      - name: manager
        image: lsstts/love-manager:develop
        ports:
        - containerPort: 8000
        command: [ "/bin/bash","-c" ]
        args:
          - cp -R /usr/src/love/manager/ /usr/src/love/manager-volume/love-manager;
            /usr/src/love/manager-volume/love-manager/runserver.sh;
        volumeMounts:
          - mountPath: /usr/src/love/manager/config # mount love.json
            name: love-conf
          - mountPath: "/usr/src/love/manager-volume"
            name: love-manager-pv-storage
        envFrom:
          - configMapRef:
              name: love-manager-env
          - configMapRef:
              name: love-manager-db-env
      volumes:
        - name: love-conf
          configMap:
            name: love-conf
            items:
              - key: love.json
                path: love.json
        - name: love-manager-pv-storage
          persistentVolumeClaim:
            claimName: love-manager-pv-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
  labels:
    app: manager-service
spec:
  ports:
  - port: 8000
  selector:
    app: manager-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-database-deployment
spec:
  selector:
    matchLabels:
      app: manager-database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: manager-database-service
    spec:
      containers:
      - name: postgres
        image: postgres:12.0
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: love-database-pv-storage
        envFrom:
          - configMapRef:
              name: love-manager-db-env
      volumes:
        - name: love-database-pv-storage
          persistentVolumeClaim:
            claimName: love-database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: manager-database-service
spec:
  ports:
  - port: 5432
  selector:
    app: manager-database-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-redis-deployment
spec:
  selector:
    matchLabels:
      app: manager-redis-service
  replicas: 1
  template:
    metadata:
      labels:
        app: manager-redis-service
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        command: [ "redis-server", "--appendonly", "yes", "--requirepass", "$(REDIS_PASS)" ] 
        ports:
          - containerPort: 6379
        envFrom:
          - configMapRef:
              name: love-manager-env
---
apiVersion: v1
kind: Service
metadata:
  name: manager-redis-service
spec:
  ports:
  - port: 6379
  selector:
    app: manager-redis-service