apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  selector:
    matchLabels:
      app: producer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer
        image: lsstts/love-producer:develop
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: love-producer-env
        env:
          - name: LOVE_CSC_PRODUCER
            value: "Test:1"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer-service
spec:
  ports:
  - port: 5000
  selector:
    app: producer-service
