version: "3.7"

services:
  #----- simulators -------
  testcsc-sim:
    image: lsstts/love-testcsc-sim:develop
    container_name: testcsc-sim-build
    environment:
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
        - ./config:/home/saluser/config/
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  atdome-sim:
    image: lsstts/love-atdome-sim:develop
    container_name: atdome-sim
    environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./config:/home/saluser/config/
    entrypoint: ["/home/saluser/atdome-setup.sh"]
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  scriptqueue-sim:
    image: lsstts/love-scriptqueue-sim:develop
    container_name: scriptqueue-sim
    environment:
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    volumes:
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  simulator:
    container_name: love-simulator
    image: lsstts/love-simulator:develop
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./config:/usr/src/love/config/
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    depends_on:
      - scriptqueue-sim
      - atdome-sim
