version: "3.4"

services:
  producer:
    container_name: love-producer
    build:
      context: ${DOCKERFILE_PATH_PRODUCER}
      dockerfile: Dockerfile
    image: love-producer-image
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - WEBSOCKET_HOST=${LOVE_PRODUCER_WEBSOCKET_HOST}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
    network_mode: ${NETWORK_NAME}

  emitter:
    container_name: love-emitter
    build:
      context: ${DOCKERFILE_PATH_EMITTER}
      dockerfile: Dockerfile
    image: love-emitter-image
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}

  manager:
    container_name: love-manager
    build:
      context: ${DOCKERFILE_PATH_MANAGER}
      dockerfile: Dockerfile
    image: love-manager-image
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=${LOVE_MANAGER_REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - AUTH_LDAP_SERVER_URI=${LOVE_MANAGER_LDAP_SERVER_URI}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
    volumes:
      - manager-volume:/usr/src/love/static
    network_mode: ${NETWORK_NAME}

  frontend:
    container_name: love-frontend
    build:
      context: ${DOCKERFILE_PATH_FRONTEND}
      args:
        WEBSOCKET_HOST: ${LOVE_FRONTEND_WEBSOCKET_HOST}
      dockerfile: Dockerfile
    image: love-frontend-image
    depends_on:
      - manager
    volumes:
      - frontend-volume:/usr/src/love
    network_mode: ${NETWORK_NAME}

  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    network_mode: ${NETWORK_NAME}

  nginx:
    container_name: love-nginx
    image: love-nginx-image
    build: ${DOCKERFILE_PATH_WEBSERVER}
    restart: always
    depends_on:
      - manager
      - frontend
    ports:
      - "80:80"
    volumes:
      - frontend-volume:/usr/src/love-frontend
      - manager-volume:/usr/src/love-manager
    network_mode: ${NETWORK_NAME}

volumes:
  frontend-volume:
  manager-volume:
