version: "3.7"

services:
  #----- simulators -------
  testcsc-sim:
    image: lsstts/love-testcsc-sim:develop
    container_name: testcsc-sim-build
    environment:
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  atdome-sim:
    image: lsstts/love-atdome-sim:develop
    container_name: atdome-sim
    entrypoint: ["/home/saluser/atdome-setup.sh"]
    environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"


  atmcs-sim:
    image: lsstts/love-atmcs-sim:develop
    container_name: atmcs-sim
    entrypoint: ["/home/saluser/atmcs-setup.sh"]
    environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  watcher-sim:
    image: lsstts/love-watcher-sim:develop
    container_name: watcher-sim
    entrypoint: ["/home/saluser/watcher-setup.sh"]
    environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  scriptqueue-sim:
    image: lsstts/love-scriptqueue-sim:develop
    container_name: scriptqueue-sim
    environment:
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  simulator:
    container_name: love-simulator
    image: lsstts/love-simulator:develop
    depends_on:
      - scriptqueue-sim
      - atdome-sim
      - testcsc-sim
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
      - ./config:/usr/src/love/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  #----- LOVE PRODUCER --------------
  producer:
    container_name: love-producer
    image: lsstts/love-producer:develop
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - WEBSOCKET_HOST=${LOVE_PRODUCER_WEBSOCKET_HOST}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
      - ./config:/usr/src/love/producer/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  #----- LOVE MANAGER --------------
  redis:
    container_name: redis
    image: redis:5.0.3
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    network_mode: ${NETWORK_NAME}
    ports:
      - "6379:6379"
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  database:
    container_name: love-database
    image: postgres:12.0
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    network_mode: ${NETWORK_NAME}
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  manager:
    container_name: love-manager
    image: lsstts/love-manager:develop
    depends_on:
      - redis
      - database
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - AUTH_LDAP_SERVER_URI=${LOVE_MANAGER_LDAP_SERVER_URI}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
      - ADMIN_USER_PASS=${ADMIN_USER_PASS}
      - USER_USER_PASS=${USER_USER_PASS}
      - CMD_USER_PASS=${CMD_USER_PASS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    network_mode: ${NETWORK_NAME}
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - manager-volume:/usr/src/love/manager/static
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  #----- LOVE FRONTEND --------------
  frontend:
    container_name: love-frontend
    image: lsstts/love-frontend:develop
    depends_on:
      - manager
    network_mode: ${NETWORK_NAME}
    volumes:
      - frontend-volume:/usr/src/love
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  nginx:
    container_name: love-nginx
    image: nginx:1.13.1
    depends_on:
      - manager
      - frontend
    network_mode: ${NETWORK_NAME}
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx-develop.conf:/etc/nginx/conf.d/default.conf
      - frontend-volume:/usr/src/love-frontend
      - manager-volume:/usr/src/love-manager
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

volumes:
  frontend-volume:
  manager-volume:
