version: "3.7"

services:
  #----- simulators -------
  atdome-sim:
    image: lsstts/love-atdome-sim:master
    container_name: atdome-sim
    environment:
        - OSPL_URI=${OSPL_URI}
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    volumes:
        - ${OSPL_CONFIG_PATH}:${OSPL_MOUNT_POINT}
        - ./config:/home/saluser/config/
    entrypoint: ["/home/saluser/atdome-setup.sh"]
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  scriptqueue-sim:
    image: lsstts/love-scriptqueue-sim:master
    container_name: scriptqueue-sim
    environment:
        - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    network_mode: ${NETWORK_NAME}
    volumes:
        - ./config:/home/saluser/config/
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  simulator:
    container_name: love-simulator
    image: lsstts/love-simulator:master
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
    volumes:
      - ./config:/usr/src/love/config/
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    depends_on:
      - scriptqueue-sim
      - atdome-sim

  #----- LOVE--------------
  producer:
    container_name: love-producer
    image: lsstts/love-producer:master
    environment:
      - LSST_DDS_DOMAIN=${LSST_DDS_DOMAIN}
      - WEBSOCKET_HOST=${LOVE_PRODUCER_WEBSOCKET_HOST}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
    volumes:
      - ./config:/usr/src/love/config/
    network_mode: ${NETWORK_NAME}

  manager:
    container_name: love-manager
    image: lsstts/love-manager:master
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=${LOVE_MANAGER_REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - AUTH_LDAP_SERVER_URI=${LOVE_MANAGER_LDAP_SERVER_URI}
      - PROCESS_CONNECTION_PASS=${PROCESS_CONNECTION_PASS}
      - ADMIN_USER_PASS=${ADMIN_USER_PASS}
      - USER_USER_PASS=${USER_USER_PASS}
      - CMD_USER_PASS=${CMD_USER_PASS}
    volumes:
      - manager-volume:/usr/src/love/static
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    depends_on:
      - redis

  frontend:
    container_name: love-frontend
    image: lsstts/love-frontend:master
    depends_on:
      - manager
    volumes:
      - frontend-volume:/usr/src/love
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

  nginx:
    container_name: love-nginx
    image: nginx:1.13.1
    restart: always
    depends_on:
      - manager
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx-master.conf:/etc/nginx/conf.d/default.conf
      - frontend-volume:/usr/src/love-frontend
      - manager-volume:/usr/src/love-manager
    network_mode: ${NETWORK_NAME}
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

volumes:
  frontend-volume:
  manager-volume:
